name: CI
on: pull_request

jobs:
  dogfooding:
    name: Dogfooding
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Eating our own dogfood
        uses: ./
