name: CI
on: pull_request

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: ShellCheck
        run: shellcheck action.sh
  dogfooding:
    name: Dogfooding
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Eating our own dogfood
        uses: ./
        with:
          skip-checkout: true
